#include "mrtdata.h"

const vector<string> mrt_names = {"admiralty", "aljunied", "angmokio", "bartley", "bayfront", "beautyworld", "bedok", "bedoknorth", "bedokreservoir", "bencoolen", "bendemeer", "bishan", "boonkeng", "boonlay", "botanicgardens", "braddell", "brasbasah", "buangkok", "bugis", "bukitbatok", "bukitgombak", "bukitpanjang", "buonavista", "caldecott", "cantonment", "cashew", "changiairport", "chinatown", "chinesegarden", "choachukang", "cityhall", "clarkequay", "clementi", "commonwealth", "dakota", "dhobyghaut", "dover", "downtown", "esplanade", "eunos", "expo", "farrerpark", "farrerroad", "fortcanning", "geylangbahru", "gulcircle", "harbourfront", "hawparvilla", "hillview", "hollandvillage", "hougang", "jalanbesar", "jookoon", "jurongeast", "kakibukit", "kallang", "kembangan", "kentridge", "keppel", "khatib", "kingalbertpark", "kovan", "kranji", "labradorpark", "lakeside", "lavender", "littleindia", "lorongchuan", "macpherson", "marinabay", "marinasouthpier", "marsiling", "marymount", "mattar", "mountbatten", "newton", "nicollhighway", "novena", "onenorth", "orchard", "outrampark", "pasirpanjang", "pasirris", "payalebar", "pioneer", "potongpasir", "princeedwardroad", "promenade", "punggol", "queenstown", "rafflesplace", "redhill", "rochor", "sembawang", "sengkang", "serangoon", "simei", "sixthavenue", "somerset", "stadium", "stevens", "taiseng", "tampines", "tampineseast", "tampineswest", "tanahmerah", "tanjongpagar", "tankahkee", "telokayer", "telokblangah", "tiongbahru", "toapayoh", "tuascrescent", "tuaslink", "tuaswestroad", "ubi", "upperchangi", "woodlands", "woodleigh","yewtee", "yiochukang", "yishun"};

unordered_map<string,vector<pair<string,int>>> mrt_adjacency_list;

unordered_map<string,string> mrt_dictionary_formatter;

unordered_map<string,string> mrt_line_grabber;

void init_mrt_adjacency_list(){
    mrt_adjacency_list["marymount"].push_back(make_pair("bishan", 2));
    mrt_adjacency_list["bishan"].push_back(make_pair("marymount", 2));
mrt_adjacency_list["bishan"].push_back(make_pair("lorongchuan", 2));
mrt_adjacency_list["lorongchuan"].push_back(make_pair("bishan", 2));
mrt_adjacency_list["lorongchuan"].push_back(make_pair("serangoon", 2));
mrt_adjacency_list["serangoon"].push_back(make_pair("lorongchuan", 2));
mrt_adjacency_list["serangoon"].push_back(make_pair("bartley", 2));
mrt_adjacency_list["bartley"].push_back(make_pair("serangoon", 2));
mrt_adjacency_list["bartley"].push_back(make_pair("taiseng", 2));
mrt_adjacency_list["taiseng"].push_back(make_pair("bartley", 2));
mrt_adjacency_list["taiseng"].push_back(make_pair("macpherson", 2));
mrt_adjacency_list["macpherson"].push_back(make_pair("taiseng", 2));
mrt_adjacency_list["macpherson"].push_back(make_pair("payalebar", 4));
mrt_adjacency_list["payalebar"].push_back(make_pair("macpherson", 4));
mrt_adjacency_list["payalebar"].push_back(make_pair("dakota", 2));
mrt_adjacency_list["dakota"].push_back(make_pair("payalebar", 2));
mrt_adjacency_list["dakota"].push_back(make_pair("mountbatten", 2));
mrt_adjacency_list["mountbatten"].push_back(make_pair("dakota", 2));
mrt_adjacency_list["mountbatten"].push_back(make_pair("stadium", 2));
mrt_adjacency_list["stadium"].push_back(make_pair("mountbatten", 2));
mrt_adjacency_list["stadium"].push_back(make_pair("nicollhighway", 2));
mrt_adjacency_list["nicollhighway"].push_back(make_pair("stadium", 2));
mrt_adjacency_list["nicollhighway"].push_back(make_pair("promenade", 2));
mrt_adjacency_list["promenade"].push_back(make_pair("nicollhighway", 2));
mrt_adjacency_list["promenade"].push_back(make_pair("esplanade", 3));
mrt_adjacency_list["esplanade"].push_back(make_pair("promenade", 3));
mrt_adjacency_list["esplanade"].push_back(make_pair("brasbasah", 3));
mrt_adjacency_list["brasbasah"].push_back(make_pair("esplanade", 3));
mrt_adjacency_list["brasbasah"].push_back(make_pair("dhobyghaut", 3));
mrt_adjacency_list["dhobyghaut"].push_back(make_pair("brasbasah", 3));
mrt_adjacency_list["promenade"].push_back(make_pair("bayfront", 2));
mrt_adjacency_list["bayfront"].push_back(make_pair("promenade", 2));
mrt_adjacency_list["bayfront"].push_back(make_pair("marinabay", 2));
mrt_adjacency_list["marinabay"].push_back(make_pair("bayfront", 2));
mrt_adjacency_list["marinabay"].push_back(make_pair("princeedwardroad", 2));
mrt_adjacency_list["princeedwardroad"].push_back(make_pair("marinabay", 2));
mrt_adjacency_list["princeedwardroad"].push_back(make_pair("cantonment", 2));
mrt_adjacency_list["cantonment"].push_back(make_pair("princeedwardroad", 2));
mrt_adjacency_list["cantonment"].push_back(make_pair("keppel", 2));
mrt_adjacency_list["keppel"].push_back(make_pair("cantonment", 2));
mrt_adjacency_list["keppel"].push_back(make_pair("harbourfront", 2));
mrt_adjacency_list["harbourfront"].push_back(make_pair("keppel", 2));
mrt_adjacency_list["harbourfront"].push_back(make_pair("telokblangah", 2));
mrt_adjacency_list["telokblangah"].push_back(make_pair("harbourfront", 2));
mrt_adjacency_list["telokblangah"].push_back(make_pair("labradorpark", 2));
mrt_adjacency_list["labradorpark"].push_back(make_pair("telokblangah", 2));
mrt_adjacency_list["labradorpark"].push_back(make_pair("pasirpanjang", 2));
mrt_adjacency_list["pasirpanjang"].push_back(make_pair("labradorpark", 2));
mrt_adjacency_list["pasirpanjang"].push_back(make_pair("hawparvilla", 2));
mrt_adjacency_list["hawparvilla"].push_back(make_pair("pasirpanjang", 2));
mrt_adjacency_list["hawparvilla"].push_back(make_pair("kentridge", 2));
mrt_adjacency_list["kentridge"].push_back(make_pair("hawparvilla", 2));
mrt_adjacency_list["kentridge"].push_back(make_pair("onenorth", 2));
mrt_adjacency_list["onenorth"].push_back(make_pair("kentridge", 2));
mrt_adjacency_list["onenorth"].push_back(make_pair("buonavista", 2));
mrt_adjacency_list["buonavista"].push_back(make_pair("onenorth", 2));
mrt_adjacency_list["buonavista"].push_back(make_pair("hollandvillage", 2));
mrt_adjacency_list["hollandvillage"].push_back(make_pair("buonavista", 2));
mrt_adjacency_list["hollandvillage"].push_back(make_pair("farrerroad", 2));
mrt_adjacency_list["farrerroad"].push_back(make_pair("hollandvillage", 2));
mrt_adjacency_list["farrerroad"].push_back(make_pair("botanicgardens", 2));
mrt_adjacency_list["botanicgardens"].push_back(make_pair("farrerroad", 2));
mrt_adjacency_list["botanicgardens"].push_back(make_pair("caldecott", 5));
mrt_adjacency_list["caldecott"].push_back(make_pair("botanicgardens", 5));
mrt_adjacency_list["caldecott"].push_back(make_pair("marymount", 2));
mrt_adjacency_list["marymount"].push_back(make_pair("caldecott", 2));
mrt_adjacency_list["jurongeast"].push_back(make_pair("bukitbatok", 3));
mrt_adjacency_list["bukitbatok"].push_back(make_pair("jurongeast", 3));
mrt_adjacency_list["bukitbatok"].push_back(make_pair("bukitgombak", 2));
mrt_adjacency_list["bukitgombak"].push_back(make_pair("bukitbatok", 2));
mrt_adjacency_list["bukitgombak"].push_back(make_pair("choachukang", 3));
mrt_adjacency_list["choachukang"].push_back(make_pair("bukitgombak", 3));
mrt_adjacency_list["choachukang"].push_back(make_pair("yewtee", 3));
mrt_adjacency_list["yewtee"].push_back(make_pair("choachukang", 3));
mrt_adjacency_list["yewtee"].push_back(make_pair("kranji", 4));
mrt_adjacency_list["kranji"].push_back(make_pair("yewtee", 4));
mrt_adjacency_list["kranji"].push_back(make_pair("marsiling", 3));
mrt_adjacency_list["marsiling"].push_back(make_pair("kranji", 3));
mrt_adjacency_list["marsiling"].push_back(make_pair("woodlands", 2));
mrt_adjacency_list["woodlands"].push_back(make_pair("marsiling", 2));
mrt_adjacency_list["woodlands"].push_back(make_pair("admiralty", 3));
mrt_adjacency_list["admiralty"].push_back(make_pair("woodlands", 3));
mrt_adjacency_list["admiralty"].push_back(make_pair("sembawang", 3));
mrt_adjacency_list["sembawang"].push_back(make_pair("admiralty", 3));
mrt_adjacency_list["sembawang"].push_back(make_pair("yishun", 3));
mrt_adjacency_list["yishun"].push_back(make_pair("sembawang", 3));
mrt_adjacency_list["yishun"].push_back(make_pair("khatib", 3));
mrt_adjacency_list["khatib"].push_back(make_pair("yishun", 3));
mrt_adjacency_list["khatib"].push_back(make_pair("yiochukang", 5));
mrt_adjacency_list["yiochukang"].push_back(make_pair("khatib", 5));
mrt_adjacency_list["yiochukang"].push_back(make_pair("angmokio", 2));
mrt_adjacency_list["angmokio"].push_back(make_pair("yiochukang", 2));
mrt_adjacency_list["angmokio"].push_back(make_pair("bishan", 3));
mrt_adjacency_list["bishan"].push_back(make_pair("angmokio", 3));
mrt_adjacency_list["bishan"].push_back(make_pair("braddell", 2));
mrt_adjacency_list["braddell"].push_back(make_pair("bishan", 2));
mrt_adjacency_list["braddell"].push_back(make_pair("toapayoh", 2));
mrt_adjacency_list["toapayoh"].push_back(make_pair("braddell", 2));
mrt_adjacency_list["toapayoh"].push_back(make_pair("novena", 2));
mrt_adjacency_list["novena"].push_back(make_pair("toapayoh", 2));
mrt_adjacency_list["novena"].push_back(make_pair("newton", 2));
mrt_adjacency_list["newton"].push_back(make_pair("novena", 2));
mrt_adjacency_list["newton"].push_back(make_pair("orchard", 2));
mrt_adjacency_list["orchard"].push_back(make_pair("newton", 2));
mrt_adjacency_list["orchard"].push_back(make_pair("somerset", 2));
mrt_adjacency_list["somerset"].push_back(make_pair("orchard", 2));
mrt_adjacency_list["somerset"].push_back(make_pair("dhobyghaut", 1));
mrt_adjacency_list["dhobyghaut"].push_back(make_pair("somerset", 1));
mrt_adjacency_list["dhobyghaut"].push_back(make_pair("cityhall", 2));
mrt_adjacency_list["cityhall"].push_back(make_pair("dhobyghaut", 2));
mrt_adjacency_list["cityhall"].push_back(make_pair("rafflesplace", 2));
mrt_adjacency_list["rafflesplace"].push_back(make_pair("cityhall", 2));
mrt_adjacency_list["rafflesplace"].push_back(make_pair("marinabay", 2));
mrt_adjacency_list["marinabay"].push_back(make_pair("rafflesplace", 2));
mrt_adjacency_list["marinabay"].push_back(make_pair("marinasouthpier", 2));
mrt_adjacency_list["marinasouthpier"].push_back(make_pair("marinabay", 2));
mrt_adjacency_list["changiairport"].push_back(make_pair("expo", 6));
mrt_adjacency_list["expo"].push_back(make_pair("changiairport", 6));
mrt_adjacency_list["expo"].push_back(make_pair("tanahmerah", 2));
mrt_adjacency_list["tanahmerah"].push_back(make_pair("expo", 2));
mrt_adjacency_list["tanahmerah"].push_back(make_pair("simei", 3));
mrt_adjacency_list["simei"].push_back(make_pair("tanahmerah", 3));
mrt_adjacency_list["simei"].push_back(make_pair("tampines", 3));
mrt_adjacency_list["tampines"].push_back(make_pair("simei", 3));
mrt_adjacency_list["tampines"].push_back(make_pair("pasirris", 3));
mrt_adjacency_list["pasirris"].push_back(make_pair("tampines", 3));
mrt_adjacency_list["tanahmerah"].push_back(make_pair("bedok", 3));
mrt_adjacency_list["bedok"].push_back(make_pair("tanahmerah", 3));
mrt_adjacency_list["bedok"].push_back(make_pair("kembangan", 3));
mrt_adjacency_list["kembangan"].push_back(make_pair("bedok", 3));
mrt_adjacency_list["kembangan"].push_back(make_pair("eunos", 2));
mrt_adjacency_list["eunos"].push_back(make_pair("kembangan", 2));
mrt_adjacency_list["eunos"].push_back(make_pair("payalebar", 2));
mrt_adjacency_list["payalebar"].push_back(make_pair("eunos", 2));
mrt_adjacency_list["payalebar"].push_back(make_pair("aljunied", 3));
mrt_adjacency_list["aljunied"].push_back(make_pair("payalebar", 3));
mrt_adjacency_list["aljunied"].push_back(make_pair("kallang", 2));
mrt_adjacency_list["kallang"].push_back(make_pair("aljunied", 2));
mrt_adjacency_list["kallang"].push_back(make_pair("lavender", 3));
mrt_adjacency_list["lavender"].push_back(make_pair("kallang", 3));
mrt_adjacency_list["lavender"].push_back(make_pair("bugis", 2));
mrt_adjacency_list["bugis"].push_back(make_pair("lavender", 2));
mrt_adjacency_list["bugis"].push_back(make_pair("cityhall", 2));
mrt_adjacency_list["cityhall"].push_back(make_pair("bugis", 2));
mrt_adjacency_list["cityhall"].push_back(make_pair("rafflesplace", 3));
mrt_adjacency_list["rafflesplace"].push_back(make_pair("cityhall", 3));
mrt_adjacency_list["rafflesplace"].push_back(make_pair("tanjongpagar", 2));
mrt_adjacency_list["tanjongpagar"].push_back(make_pair("rafflesplace", 2));
mrt_adjacency_list["tanjongpagar"].push_back(make_pair("outrampark", 2));
mrt_adjacency_list["outrampark"].push_back(make_pair("tanjongpagar", 2));
mrt_adjacency_list["outrampark"].push_back(make_pair("tiongbahru", 3));
mrt_adjacency_list["tiongbahru"].push_back(make_pair("outrampark", 3));
mrt_adjacency_list["tiongbahru"].push_back(make_pair("redhill", 3));
mrt_adjacency_list["redhill"].push_back(make_pair("tiongbahru", 3));
mrt_adjacency_list["redhill"].push_back(make_pair("queenstown", 2));
mrt_adjacency_list["queenstown"].push_back(make_pair("redhill", 2));
mrt_adjacency_list["queenstown"].push_back(make_pair("commonwealth", 3));
mrt_adjacency_list["commonwealth"].push_back(make_pair("queenstown", 3));
mrt_adjacency_list["commonwealth"].push_back(make_pair("buonavista", 2));
mrt_adjacency_list["buonavista"].push_back(make_pair("commonwealth", 2));
mrt_adjacency_list["buonavista"].push_back(make_pair("dover", 3));
mrt_adjacency_list["dover"].push_back(make_pair("buonavista", 3));
mrt_adjacency_list["dover"].push_back(make_pair("clementi", 2));
mrt_adjacency_list["clementi"].push_back(make_pair("dover", 2));
mrt_adjacency_list["clementi"].push_back(make_pair("jurongeast", 5));
mrt_adjacency_list["jurongeast"].push_back(make_pair("clementi", 5));
mrt_adjacency_list["jurongeast"].push_back(make_pair("chinesegarden", 2));
mrt_adjacency_list["chinesegarden"].push_back(make_pair("jurongeast", 2));
mrt_adjacency_list["chinesegarden"].push_back(make_pair("lakeside", 3));
mrt_adjacency_list["lakeside"].push_back(make_pair("chinesegarden", 3));
mrt_adjacency_list["lakeside"].push_back(make_pair("boonlay", 2));
mrt_adjacency_list["boonlay"].push_back(make_pair("lakeside", 2));
mrt_adjacency_list["boonlay"].push_back(make_pair("pioneer", 3));
mrt_adjacency_list["pioneer"].push_back(make_pair("boonlay", 3));
mrt_adjacency_list["pioneer"].push_back(make_pair("jookoon", 3));
mrt_adjacency_list["jookoon"].push_back(make_pair("pioneer", 3));
mrt_adjacency_list["jookoon"].push_back(make_pair("gulcircle", 3));
mrt_adjacency_list["gulcircle"].push_back(make_pair("jookoon", 3));
mrt_adjacency_list["gulcircle"].push_back(make_pair("tuascrescent", 3));
mrt_adjacency_list["tuascrescent"].push_back(make_pair("gulcircle", 3));
mrt_adjacency_list["tuascrescent"].push_back(make_pair("tuaswestroad", 2));
mrt_adjacency_list["tuaswestroad"].push_back(make_pair("tuascrescent", 2));
mrt_adjacency_list["tuaswestroad"].push_back(make_pair("tuaslink", 2));
mrt_adjacency_list["tuaslink"].push_back(make_pair("tuaswestroad", 2));
mrt_adjacency_list["bukitpanjang"].push_back(make_pair("cashew", 2));
mrt_adjacency_list["cashew"].push_back(make_pair("bukitpanjang", 2));
mrt_adjacency_list["cashew"].push_back(make_pair("hillview", 1));
mrt_adjacency_list["hillview"].push_back(make_pair("cashew", 1));
mrt_adjacency_list["hillview"].push_back(make_pair("beautyworld", 4));
mrt_adjacency_list["beautyworld"].push_back(make_pair("hillview", 4));
mrt_adjacency_list["beautyworld"].push_back(make_pair("kingalbertpark", 2));
mrt_adjacency_list["kingalbertpark"].push_back(make_pair("beautyworld", 2));
mrt_adjacency_list["kingalbertpark"].push_back(make_pair("sixthavenue", 2));
mrt_adjacency_list["sixthavenue"].push_back(make_pair("kingalbertpark", 2));
mrt_adjacency_list["sixthavenue"].push_back(make_pair("tankahkee", 2));
mrt_adjacency_list["tankahkee"].push_back(make_pair("sixthavenue", 2));
mrt_adjacency_list["tankahkee"].push_back(make_pair("botanicgardens", 2));
mrt_adjacency_list["botanicgardens"].push_back(make_pair("tankahkee", 2));
mrt_adjacency_list["botanicgardens"].push_back(make_pair("stevens", 2));
mrt_adjacency_list["stevens"].push_back(make_pair("botanicgardens", 2));
mrt_adjacency_list["stevens"].push_back(make_pair("newton", 2));
mrt_adjacency_list["newton"].push_back(make_pair("stevens", 2));
mrt_adjacency_list["newton"].push_back(make_pair("littleindia", 2));
mrt_adjacency_list["littleindia"].push_back(make_pair("newton", 2));
mrt_adjacency_list["littleindia"].push_back(make_pair("rochor", 2));
mrt_adjacency_list["rochor"].push_back(make_pair("littleindia", 2));
mrt_adjacency_list["rochor"].push_back(make_pair("bugis", 2));
mrt_adjacency_list["bugis"].push_back(make_pair("rochor", 2));
mrt_adjacency_list["bugis"].push_back(make_pair("promenade", 2));
mrt_adjacency_list["promenade"].push_back(make_pair("bugis", 2));
mrt_adjacency_list["promenade"].push_back(make_pair("bayfront", 2));
mrt_adjacency_list["bayfront"].push_back(make_pair("promenade", 2));
mrt_adjacency_list["bayfront"].push_back(make_pair("downtown", 2));
mrt_adjacency_list["downtown"].push_back(make_pair("bayfront", 2));
mrt_adjacency_list["downtown"].push_back(make_pair("telokayer", 1));
mrt_adjacency_list["telokayer"].push_back(make_pair("downtown", 1));
mrt_adjacency_list["telokayer"].push_back(make_pair("chinatown", 1));
mrt_adjacency_list["chinatown"].push_back(make_pair("telokayer", 1));
mrt_adjacency_list["chinatown"].push_back(make_pair("fortcanning", 3));
mrt_adjacency_list["fortcanning"].push_back(make_pair("chinatown", 3));
mrt_adjacency_list["fortcanning"].push_back(make_pair("bencoolen", 1));
mrt_adjacency_list["bencoolen"].push_back(make_pair("fortcanning", 1));
mrt_adjacency_list["bencoolen"].push_back(make_pair("jalanbesar", 2));
mrt_adjacency_list["jalanbesar"].push_back(make_pair("bencoolen", 2));
mrt_adjacency_list["jalanbesar"].push_back(make_pair("bendemeer", 2));
mrt_adjacency_list["bendemeer"].push_back(make_pair("jalanbesar", 2));
mrt_adjacency_list["bendemeer"].push_back(make_pair("geylangbahru", 2));
mrt_adjacency_list["geylangbahru"].push_back(make_pair("bendemeer", 2));
mrt_adjacency_list["geylangbahru"].push_back(make_pair("mattar", 3));
mrt_adjacency_list["mattar"].push_back(make_pair("geylangbahru", 3));
mrt_adjacency_list["mattar"].push_back(make_pair("macpherson", 1));
mrt_adjacency_list["macpherson"].push_back(make_pair("mattar", 1));
mrt_adjacency_list["macpherson"].push_back(make_pair("ubi", 2));
mrt_adjacency_list["ubi"].push_back(make_pair("macpherson", 2));
mrt_adjacency_list["ubi"].push_back(make_pair("kakibukit", 2));
mrt_adjacency_list["kakibukit"].push_back(make_pair("ubi", 2));
mrt_adjacency_list["kakibukit"].push_back(make_pair("bedoknorth", 2));
mrt_adjacency_list["bedoknorth"].push_back(make_pair("kakibukit", 2));
mrt_adjacency_list["bedoknorth"].push_back(make_pair("bedokreservoir", 2));
mrt_adjacency_list["bedokreservoir"].push_back(make_pair("bedoknorth", 2));
mrt_adjacency_list["bedokreservoir"].push_back(make_pair("tampineswest", 3));
mrt_adjacency_list["tampineswest"].push_back(make_pair("bedokreservoir", 3));
mrt_adjacency_list["tampineswest"].push_back(make_pair("tampines", 2));
mrt_adjacency_list["tampines"].push_back(make_pair("tampineswest", 2));
mrt_adjacency_list["tampines"].push_back(make_pair("tampineseast", 2));
mrt_adjacency_list["tampineseast"].push_back(make_pair("tampines", 2));
mrt_adjacency_list["tampineseast"].push_back(make_pair("upperchangi", 3));
mrt_adjacency_list["upperchangi"].push_back(make_pair("tampineseast", 3));
mrt_adjacency_list["upperchangi"].push_back(make_pair("expo", 2));
mrt_adjacency_list["expo"].push_back(make_pair("upperchangi", 2));
mrt_adjacency_list["punggol"].push_back(make_pair("sengkang", 2));
mrt_adjacency_list["sengkang"].push_back(make_pair("punggol", 2));
mrt_adjacency_list["sengkang"].push_back(make_pair("buangkok", 2));
mrt_adjacency_list["buangkok"].push_back(make_pair("sengkang", 2));
mrt_adjacency_list["buangkok"].push_back(make_pair("hougang", 2));
mrt_adjacency_list["hougang"].push_back(make_pair("buangkok", 2));
mrt_adjacency_list["hougang"].push_back(make_pair("kovan", 3));
mrt_adjacency_list["kovan"].push_back(make_pair("hougang", 3));
mrt_adjacency_list["kovan"].push_back(make_pair("serangoon", 2));
mrt_adjacency_list["serangoon"].push_back(make_pair("kovan", 2));
mrt_adjacency_list["serangoon"].push_back(make_pair("woodleigh", 2));
mrt_adjacency_list["woodleigh"].push_back(make_pair("serangoon", 2));
mrt_adjacency_list["woodleigh"].push_back(make_pair("potongpasir", 2));
mrt_adjacency_list["potongpasir"].push_back(make_pair("woodleigh", 2));
mrt_adjacency_list["potongpasir"].push_back(make_pair("boonkeng", 2));
mrt_adjacency_list["boonkeng"].push_back(make_pair("potongpasir", 2));
mrt_adjacency_list["boonkeng"].push_back(make_pair("farrerpark", 2));
mrt_adjacency_list["farrerpark"].push_back(make_pair("boonkeng", 2));
mrt_adjacency_list["farrerpark"].push_back(make_pair("littleindia", 2));
mrt_adjacency_list["littleindia"].push_back(make_pair("farrerpark", 2));
mrt_adjacency_list["littleindia"].push_back(make_pair("dhobyghaut", 2));
mrt_adjacency_list["dhobyghaut"].push_back(make_pair("littleindia", 2));
mrt_adjacency_list["dhobyghaut"].push_back(make_pair("clarkequay", 3));
mrt_adjacency_list["clarkequay"].push_back(make_pair("dhobyghaut", 3));
mrt_adjacency_list["clarkequay"].push_back(make_pair("chinatown", 1));
mrt_adjacency_list["chinatown"].push_back(make_pair("clarkequay", 1));
mrt_adjacency_list["chinatown"].push_back(make_pair("outrampark", 2));
mrt_adjacency_list["outrampark"].push_back(make_pair("chinatown", 2));
mrt_adjacency_list["outrampark"].push_back(make_pair("harbourfront", 4));
mrt_adjacency_list["harbourfront"].push_back(make_pair("outrampark", 4));}

void init_mrt_dictionary_formatter() {
    mrt_dictionary_formatter["admiralty"] = "Admiralty";
mrt_dictionary_formatter["aljunied"] = "Aljunied";
mrt_dictionary_formatter["angmokio"] = "Ang Mo Kio";
mrt_dictionary_formatter["bartley"] = "Bartley";
mrt_dictionary_formatter["bayfront"] = "Bayfront";
mrt_dictionary_formatter["beautyworld"] = "Beauty World";
mrt_dictionary_formatter["bedok"] = "Bedok";
mrt_dictionary_formatter["bedoknorth"] = "Bedok North";
mrt_dictionary_formatter["bedokreservoir"] = "Bedok Reservoir";
mrt_dictionary_formatter["bencoolen"] = "Bencoolen";
mrt_dictionary_formatter["bendemeer"] = "Bendemeer";
mrt_dictionary_formatter["bishan"] = "Bishan";
mrt_dictionary_formatter["boonkeng"] = "Boon Keng";
mrt_dictionary_formatter["boonlay"] = "Boon Lay";
mrt_dictionary_formatter["botanicgardens"] = "Botanic Gardens";
mrt_dictionary_formatter["braddell"] = "Braddell";
mrt_dictionary_formatter["brasbasah"] = "Bras Basah";
mrt_dictionary_formatter["buangkok"] = "Buangkok";
mrt_dictionary_formatter["bugis"] = "Bugis";
mrt_dictionary_formatter["bukitbatok"] = "Bukit Batok";
mrt_dictionary_formatter["bukitgombak"] = "Bukit Gombak";
mrt_dictionary_formatter["bukitpanjang"] = "Bukit Panjang";
mrt_dictionary_formatter["buonavista"] = "Buona Vista";
mrt_dictionary_formatter["caldecott"] = "Caldecott";
mrt_dictionary_formatter["cantonment"] = "Cantonment";
mrt_dictionary_formatter["cashew"] = "Cashew";
mrt_dictionary_formatter["changiairport"] = "Changi Airport";
mrt_dictionary_formatter["chinatown"] = "Chinatown";
mrt_dictionary_formatter["chinesegarden"] = "Chinese Garden";
mrt_dictionary_formatter["choachukang"] = "Choa Chu Kang";
mrt_dictionary_formatter["cityhall"] = "City Hall";
mrt_dictionary_formatter["clarkequay"] = "Clarke Quay";
mrt_dictionary_formatter["clementi"] = "Clementi";
mrt_dictionary_formatter["commonwealth"] = "Commonwealth";
mrt_dictionary_formatter["dakota"] = "Dakota";
mrt_dictionary_formatter["dhobyghaut"] = "Dhoby Ghaut";
mrt_dictionary_formatter["dover"] = "Dover";
mrt_dictionary_formatter["downtown"] = "Downtown";
mrt_dictionary_formatter["esplanade"] = "Esplanade";
mrt_dictionary_formatter["eunos"] = "Eunos";
mrt_dictionary_formatter["expo"] = "Expo";
mrt_dictionary_formatter["farrerpark"] = "Farrer Park";
mrt_dictionary_formatter["farrerroad"] = "Farrer Road";
mrt_dictionary_formatter["fortcanning"] = "Fort Canning";
mrt_dictionary_formatter["geylangbahru"] = "Geylang Bahru";
mrt_dictionary_formatter["gulcircle"] = "Gul Circle";
mrt_dictionary_formatter["harbourfront"] = "HarbourFront";
mrt_dictionary_formatter["hawparvilla"] = "Haw Par Villa";
mrt_dictionary_formatter["hillview"] = "Hillview";
mrt_dictionary_formatter["hollandvillage"] = "Holland Village";
mrt_dictionary_formatter["hougang"] = "Hougang";
mrt_dictionary_formatter["jalanbesar"] = "Jalan Besar";
mrt_dictionary_formatter["jookoon"] = "Joo Koon";
mrt_dictionary_formatter["jurongeast"] = "Jurong East";
mrt_dictionary_formatter["kakibukit"] = "Kaki Bukit";
mrt_dictionary_formatter["kallang"] = "Kallang";
mrt_dictionary_formatter["kembangan"] = "Kembangan";
mrt_dictionary_formatter["kentridge"] = "Kent Ridge";
mrt_dictionary_formatter["keppel"] = "Keppel";
mrt_dictionary_formatter["khatib"] = "Khatib";
mrt_dictionary_formatter["kingalbertpark"] = "King Albert Park";
mrt_dictionary_formatter["kovan"] = "Kovan";
mrt_dictionary_formatter["kranji"] = "Kranji";
mrt_dictionary_formatter["labradorpark"] = "Labrador Park";
mrt_dictionary_formatter["lakeside"] = "Lakeside";
mrt_dictionary_formatter["lavender"] = "Lavender";
mrt_dictionary_formatter["littleindia"] = "Little India";
mrt_dictionary_formatter["lorongchuan"] = "Lorong Chuan";
mrt_dictionary_formatter["macpherson"] = "MacPherson";
mrt_dictionary_formatter["marinabay"] = "Marina Bay";
mrt_dictionary_formatter["marinasouthpier"] = "Marina South Pier";
mrt_dictionary_formatter["marsiling"] = "Marsiling";
mrt_dictionary_formatter["marymount"] = "Marymount";
mrt_dictionary_formatter["mattar"] = "Mattar";
mrt_dictionary_formatter["mountbatten"] = "Mountbatten";
mrt_dictionary_formatter["newton"] = "Newton";
mrt_dictionary_formatter["nicollhighway"] = "Nicoll Highway";
mrt_dictionary_formatter["novena"] = "Novena";
mrt_dictionary_formatter["onenorth"] = "One-North";
mrt_dictionary_formatter["orchard"] = "Orchard";
mrt_dictionary_formatter["outrampark"] = "Outram Park";
mrt_dictionary_formatter["pasirpanjang"] = "Pasir Panjang";
mrt_dictionary_formatter["pasirris"] = "Pasir Ris";
mrt_dictionary_formatter["payalebar"] = "Paya Lebar";
mrt_dictionary_formatter["pioneer"] = "Pioneer";
mrt_dictionary_formatter["potongpasir"] = "Potong Pasir";
mrt_dictionary_formatter["princeedwardroad"] = "Prince Edward Road";
mrt_dictionary_formatter["promenade"] = "Promenade";
mrt_dictionary_formatter["punggol"] = "Punggol";
mrt_dictionary_formatter["queenstown"] = "Queenstown";
mrt_dictionary_formatter["rafflesplace"] = "Raffles Place";
mrt_dictionary_formatter["redhill"] = "Redhill";
mrt_dictionary_formatter["rochor"] = "Rochor";
mrt_dictionary_formatter["sembawang"] = "Sembawang";
mrt_dictionary_formatter["sengkang"] = "Sengkang";
mrt_dictionary_formatter["serangoon"] = "Serangoon";
mrt_dictionary_formatter["simei"] = "Simei";
mrt_dictionary_formatter["sixthavenue"] = "Sixth Avenue";
mrt_dictionary_formatter["somerset"] = "Somerset";
mrt_dictionary_formatter["stadium"] = "Stadium";
mrt_dictionary_formatter["stevens"] = "Stevens";
mrt_dictionary_formatter["taiseng"] = "Tai Seng";
mrt_dictionary_formatter["tampines"] = "Tampines";
mrt_dictionary_formatter["tampineseast"] = "Tampines East";
mrt_dictionary_formatter["tampineswest"] = "Tampines West";
mrt_dictionary_formatter["tanahmerah"] = "Tanah Merah";
mrt_dictionary_formatter["tanjongpagar"] = "Tanjong Pagar";
mrt_dictionary_formatter["tankahkee"] = "Tan Kah Kee";
mrt_dictionary_formatter["telokayer"] = "Telok Ayer";
mrt_dictionary_formatter["telokblangah"] = "Telok Blangah";
mrt_dictionary_formatter["tiongbahru"] = "Tiong Bahru";
mrt_dictionary_formatter["toapayoh"] = "Toa Payoh";
mrt_dictionary_formatter["tuascrescent"] = "Tuas Crescent";
mrt_dictionary_formatter["tuaslink"] = "Tuas Link";
mrt_dictionary_formatter["tuaswestroad"] = "Tuas West Road";
mrt_dictionary_formatter["ubi"] = "Ubi";
mrt_dictionary_formatter["upperchangi"] = "Upper Changi";
mrt_dictionary_formatter["woodlands"] = "Woodlands";
mrt_dictionary_formatter["woodleigh"] = "Woodleigh";
mrt_dictionary_formatter["yewtee"] = "Yew Tee";
mrt_dictionary_formatter["yiochukang"] = "Yio Chu Kang";
mrt_dictionary_formatter["yishun"] = "Yishun";

}

void init_mrt_line_grabber() {
mrt_line_grabber["admiralty"] = "NSL";
mrt_line_grabber["aljunied"] = "EWL";
mrt_line_grabber["angmokio"] = "NSL";
mrt_line_grabber["bartley"] = "CCL";
mrt_line_grabber["bayfront"] = "DTL";
mrt_line_grabber["beautyworld"] = "DTL";
mrt_line_grabber["bedok"] = "EWL";
mrt_line_grabber["bedoknorth"] = "DTL";
mrt_line_grabber["bedokreservoir"] = "DTL";
mrt_line_grabber["bencoolen"] = "DTL";
mrt_line_grabber["bendemeer"] = "DTL";
mrt_line_grabber["bishan"] = "NSL";
mrt_line_grabber["boonkeng"] = "NEL";
mrt_line_grabber["boonlay"] = "EWL";
mrt_line_grabber["botanicgardens"] = "DTL";
mrt_line_grabber["braddell"] = "NSL";
mrt_line_grabber["brasbasah"] = "CCL";
mrt_line_grabber["buangkok"] = "NEL";
mrt_line_grabber["bugis"] = "DTL";
mrt_line_grabber["bukitbatok"] = "NSL";
mrt_line_grabber["bukitgombak"] = "NSL";
mrt_line_grabber["bukitpanjang"] = "DTL";
mrt_line_grabber["buonavista"] = "EWL";
mrt_line_grabber["caldecott"] = "CCL";
mrt_line_grabber["cantonment"] = "CCL";
mrt_line_grabber["cashew"] = "DTL";
mrt_line_grabber["changiairport"] = "EWL";
mrt_line_grabber["chinatown"] = "DTL";
mrt_line_grabber["chinesegarden"] = "EWL";
mrt_line_grabber["choachukang"] = "NSL";
mrt_line_grabber["cityhall"] = "NSL";
mrt_line_grabber["clarkequay"] = "NEL";
mrt_line_grabber["clementi"] = "EWL";
mrt_line_grabber["commonwealth"] = "EWL";
mrt_line_grabber["dakota"] = "CCL";
mrt_line_grabber["dhobyghaut"] = "NSL";
mrt_line_grabber["dover"] = "EWL";
mrt_line_grabber["downtown"] = "DTL";
mrt_line_grabber["esplanade"] = "CCL";
mrt_line_grabber["eunos"] = "EWL";
mrt_line_grabber["expo"] = "EWL";
mrt_line_grabber["farrerpark"] = "NEL";
mrt_line_grabber["farrerroad"] = "CCL";
mrt_line_grabber["fortcanning"] = "DTL";
mrt_line_grabber["geylangbahru"] = "DTL";
mrt_line_grabber["gulcircle"] = "EWL";
mrt_line_grabber["harbourfront"] = "NEL";
mrt_line_grabber["hawparvilla"] = "CCL";
mrt_line_grabber["hillview"] = "DTL";
mrt_line_grabber["hollandvillage"] = "CCL";
mrt_line_grabber["hougang"] = "NEL";
mrt_line_grabber["jalanbesar"] = "DTL";
mrt_line_grabber["jookoon"] = "EWL";
mrt_line_grabber["jurongeast"] = "NSL";
mrt_line_grabber["kakibukit"] = "DTL";
mrt_line_grabber["kallang"] = "EWL";
mrt_line_grabber["kembangan"] = "EWL";
mrt_line_grabber["kentridge"] = "CCL";
mrt_line_grabber["keppel"] = "CCL";
mrt_line_grabber["khatib"] = "NSL";
mrt_line_grabber["kingalbertpark"] = "DTL";
mrt_line_grabber["kovan"] = "NEL";
mrt_line_grabber["kranji"] = "NSL";
mrt_line_grabber["labradorpark"] = "CCL";
mrt_line_grabber["lakeside"] = "EWL";
mrt_line_grabber["lavender"] = "EWL";
mrt_line_grabber["littleindia"] = "DTL";
mrt_line_grabber["lorongchuan"] = "CCL";
mrt_line_grabber["macpherson"] = "CCL";
mrt_line_grabber["marinabay"] = "NSL";
mrt_line_grabber["marinasouthpier"] = "NSL";
mrt_line_grabber["marsiling"] = "NSL";
mrt_line_grabber["marymount"] = "CCL";
mrt_line_grabber["mattar"] = "DTL";
mrt_line_grabber["mountbatten"] = "CCL";
mrt_line_grabber["newton"] = "DTL";
mrt_line_grabber["nicollhighway"] = "CCL";
mrt_line_grabber["novena"] = "NSL";
mrt_line_grabber["onenorth"] = "CCL";
mrt_line_grabber["orchard"] = "NSL";
mrt_line_grabber["outrampark"] = "NEL";
mrt_line_grabber["pasirpanjang"] = "CCL";
mrt_line_grabber["pasirris"] = "EWL";
mrt_line_grabber["payalebar"] = "EWL";
mrt_line_grabber["pioneer"] = "EWL";
mrt_line_grabber["potongpasir"] = "NEL";
mrt_line_grabber["princeedwardroad"] = "CCL";
mrt_line_grabber["promenade"] = "CCL";
mrt_line_grabber["punggol"] = "NEL";
mrt_line_grabber["queenstown"] = "EWL";
mrt_line_grabber["rafflesplace"] = "NSL";
mrt_line_grabber["redhill"] = "EWL";
mrt_line_grabber["rochor"] = "DTL";
mrt_line_grabber["sembawang"] = "NSL";
mrt_line_grabber["sengkang"] = "NEL";
mrt_line_grabber["serangoon"] = "NEL";
mrt_line_grabber["simei"] = "EWL";
mrt_line_grabber["sixthavenue"] = "DTL";
mrt_line_grabber["somerset"] = "NSL";
mrt_line_grabber["stadium"] = "CCL";
mrt_line_grabber["stevens"] = "DTL";
mrt_line_grabber["taiseng"] = "CCL";
mrt_line_grabber["tampines"] = "EWL";
mrt_line_grabber["tampineseast"] = "DTL";
mrt_line_grabber["tampineswest"] = "DTL";
mrt_line_grabber["tanahmerah"] = "EWL";
mrt_line_grabber["tanjongpagar"] = "NSL";
mrt_line_grabber["telokayer"] = "DTL";
mrt_line_grabber["telokblangah"] = "CCL";
mrt_line_grabber["tiongbahru"] = "EWL";
mrt_line_grabber["toapayoh"] = "NSL";
mrt_line_grabber["tuascrescent"] = "EWL";
mrt_line_grabber["tuaslink"] = "EWL";
mrt_line_grabber["tuaswestroad"] = "EWL";
mrt_line_grabber["ubi"] = "DTL";
mrt_line_grabber["upperchangi"] = "DTL";
mrt_line_grabber["woodlands"] = "NSL";
mrt_line_grabber["woodleigh"] = "NEL";
mrt_line_grabber["yewtee"] = "NSL";
mrt_line_grabber["yiochukang"] = "NSL";
mrt_line_grabber["yishun"] = "NSL";

}